function y = Rectangular_01(x)
%RECTANGULAR_01 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 24-Dec-2023 00:53:22

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % FIR Window Lowpass filter designed using the FIR1 function.
    %
    % % All frequency values are in Hz.
    % Fs = 48000;  % Sampling Frequency
    %
    % N    = 10;       % Order
    % Fc   = 10800;    % Cutoff Frequency
    % flag = 'scale';  % Sampling Flag
    %
    % % Create the window vector for the design algorithm.
    % win = barthannwin(N+1);
    %
    % % Calculate the coefficients using the FIR1 function.
    % b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [0 -0.00571414673746954 -0.0343461882499669 ...
        0.0319624391033263 0.280130327932248 0.455935135903724 0.280130327932248 ...
        0.0319624391033263 -0.0343461882499669 -0.00571414673746954 0]);
end

y = step(Hd,x);


% [EOF]
