function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 23-May-2022 23:42:12

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'PlotBoxAspectRatio',[1 1.08333333333333 1.66666666666667],...
    'DataAspectRatio',[1 1 1]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1.2]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1.3]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',3.5);

% Create xlabel
xlabel('Voltage(V)');

% Create ylabel
ylabel('Current(mA)');

% Create title
title('Voltage across vs Current through Diode');

